arco-design/arco-design-mobile

README.md
README.zh-CN.md

1.添加Less,TypeScript,React.js标签，让大家从文档一眼就看出技术栈是什么
2.添加npm的版本号标签和npm的下载量标签(标签中的变量和npm绑定,数值会自动改变)
合并理由如下：
1.由一个标签变成了两排六个标签，原来的license标签不再孤单，而且也好看一些
2.可以动态地看到npm的版本号和月下载量,可视化了arco-design的发展，也许看到是新起的，大家会更加踊跃地提出pr

docs: add ShieldsIO tags to README

---

packages/arcodesign/components/tabs/tab-pane.tsx

通过限制最大的滚动距离来修复 #36，本地测试 work
iOS 的 scrollTop 没有按照[规范](https://drafts.csswg.org/cssom-view/#dom-window-scroll:~:text=If%20the%20viewport%20has%20downward,area%20height%20%2D%20viewport%20height)限制最大值，赋值超出范围会实时生效，影响 Sticky 的判断，测试 iOS 13 - 15 均有此问题，因此在 js 层面限制最大滚动距离 🤣

fix: `Tabs` limit max scroll distance close

---

packages/arcodesign/components/nav-bar/index.tsx

我现在使用 NextJs 13 版本配置了 Arco-Design-react，在使用 NavBar 的时候提示了我 “op `style` did not match. Server: "null" Client: "padding-top:"” 的 warning，我发现在 Next.js 中，在服务端使用 createElement 生成 React Element 时，如果 style 属性的值为空字符串或 undefined，它会被替换成 null，原因是为了将其与行内样式混淆的情况区分开来，所以当 paddingTop 为空值时，我们最好默认它为 “0px”。

fix: `NavBar` fix warning in nextjs ssr

---

sites/pc/entry/index.less
sites/pc/entry/layout/index.less

[bugfix] 修复了 站点 mobile/react/arco-design/pc/#/doc/changelog 中li元素因换行导致的样式重叠问题

site: fix li element overflow

---

packages/arcodesign/components/image-preview/index.tsx

问题描述：多张图片组件预览时，第一次打开黑屏，图片不显示
问题分析：
setImagesStatusByIndex  setImagesStatus
如果两张图片的onload事件同时到达，此时render没有来得刷新，会出现在一次render期间
setImagesStatus被调用两次，
第一次刷新时根据 imagesStatusRef.current 来计算
setImagesStatus 之后imagesStatusRef.current值没有立即改变
第二次刷新时也根据 imagesStatusRef.current 来计算
覆盖了第一次刷新的结果，导致第一张图片的loaded状态一直为false

fix: `ImagePreview` refresh problem when onload of multiple pictures is triggered at the same time

---

packages/arcodesign/components/checkbox/style/index.less
packages/arcodesign/components/radio/style/index.less
packages/arcodesign/components/switch/style/index.less
packages/common-widgets/style/reset.less
scripts/sites/webpack.dev.home.js
scripts/sites/webpack.dev.mobile.js
scripts/sites/webpack.dev.pc.js

fix: style problem caused by the "tabIndex" attribute of lower versions of iOS

---

packages/arcodesign/components/tabs/index.tsx

fix: `Tabs` trigger "onChange" before distance is set to 0

---

packages/arcodesign/components/ellipsis/components/js-ellipsis.tsx

在一个有展开收起的例子中。比如
```tsx
import { Ellipsis } from '@arco-design/mobile-react';
export default function EllipsisDemo() {
const text =
`This wasn't the first time ''natural'' sounds had been used in musical compositions; that sort of thing had been going on at least as far back as the 19th century, and the surrealists and futurists of the 1920s and 1930s were way into this kind of thing.`;
const [ellipsis, setEllipsis] = React.useState(true);
const collapseNode = <span className="demo-link">Collapse</span>;
return (
<Ellipsis
ellipsis={ellipsis}
text={text}
maxLine={2}
ellipsisNode={
<span>
...<span className="demo-link">Expand</span>
</span>
}
collapseNode={collapseNode}
reflowOnResize={true}
onEllipsisNodeClick={() => {
setEllipsis(false);
}}
onCollapseNodeClick={() => {
setEllipsis(true); …
```

fix: `Ellipsis` use ellipsisValueRef to reduce reflow

---

packages/arcodesign/components/avatar/__test__/index.spec.js
packages/arcodesign/components/badge/__test__/index.spec.js
packages/arcodesign/components/loading/__test__/index.spec.js
packages/arcodesign/components/radio/__test__/index.spec.js
packages/arcodesign/components/tag/__test__/index.spec.js

This pull request refactors the component tests for the `Avatar`, `Badge`, `Loading`, `Radio`, and `Tag` components.

test: refactor component tests for the `Avatar`, `Badge`, `Loading`, `Radio`, and `Tag` components.

---

.github/workflows/pr-preview.yml
.gitignore
sites/home/inject/inject.config.js
sites/pc/inject/inject.config.js

This pull request introduces a new GitHub Actions workflow for generating and deploying a preview of the site when a pull request is made. 
此 PR 引入了一个新的 GitHub Actions 工作流程，用于在创建 PR 自动部署网站的预览，可以更方便的检查文档站和组件效果。
* [`.github/workflows/pr-preview.yml`](diffhunk://#diff-737d2247cd4b3b6578d2c5413b555a5ca90f6aaa32613770ffdc146900d0469bR1-R83): Added a new workflow named "PR Preview" that builds and deploys a preview of the site for pull requests to Surge and comments the preview link on the pull request.
* [`sites/home/inject/inject.config.js`](diffhunk://#diff-065a3b3df2121fd63f642b07046b706d2c8d8e9bacb5a87e6307a476967decddL2-R2): Updated the `$siteDomain
variable to use the `ARCO_SITE_DOMAIN` environment variable if it is set, otherwise defaulting to 'arco.design'.
* …

feat: Add workflow for PR preview deployment

---

packages/arcodesign/components/_helpers/hooks.ts

this pr is about fix `hooks.ts` `useMountedState` not working correctly in React 18 with StrictMode.
StrictMode will render component twice,  but in `useMountedState` do not have code to re-init `leavingRef` when mounted again.
- [aHooks - useUnmountedRef](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useUnmountedRef/index.tsx)
- [aHooks - useSafeState](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useSafeState/index.ts)
when i using `Picker` component, its data will not correctly updated after select `PickerCell` items.
related #291
- `image`
- `picker-view`
- `popover`

fix: fix `useMountedState` in `hooks.ts` not correct init leavingRef in StrictMode.

---

packages/arcodesign/components/date-picker/index.tsx
packages/arcodesign/components/date-picker/type.ts

This pull request includes updates to the `DatePicker` component in the `packages/arcodesign` directory. The changes focus on handling empty values more gracefully in the `renderLinkedContainer` function.
Key changes:
* [`packages/arcodesign/components/date-picker/index.tsx`](diffhunk://#diff-10735aee4cdb6d455cc93497bf98499d7c6152137ddca7623f2d6b561babf68eL10-R10): Added `isEmptyValue` import from `@arco-design/mobile-utils` to check for empty values.
* [`packages/arcodesign/components/date-picker/index.tsx`](diffhunk://#diff-10735aee4cdb6d455cc93497bf98499d7c6152137ddca7623f2d6b561babf68eL295-R299): Updated `renderLinkedContainer` to handle cases where `props.currentTs` is empty by passing `undefined` instead of `currentTs`.
* [`packages/arcodesign/components/date-picker/type.ts`](diffhun …

fix: keep empty value in renderLinkedContainer of `DatePicker`

---

packages/arcodesign/components/_helpers/hooks.ts
packages/common-widgets/utils/browser.ts
sites/pc/docOutput/function/browser.README.md
sites/pc/docOutput/function/hooks/hooks.README.md

This pull request introduces several changes to improve the detection of the HarmonyOS operating system in the `arco-design` package. The most significant changes include updates to the `useSystem` hook and the `getSystem` utility function to support an optional configuration for detecting HarmonyOS.
Enhancements to OS detection:
* [`packages/arcodesign/components/_helpers/hooks.ts`](diffhunk://#diff-c09413cb5bf6a983e28de9e244bdf9efe4419b4f675e73d6b79e5015127fc9c7L220-R244): Added a new parameter `options` to the `useSystem` function, allowing the detection of HarmonyOS separately. Updated the function to use this parameter when determining the operating system.
* [`packages/common-widgets/utils/browser.ts`](diffhunk://#diff-10fbf67be2e0f5337cfbbd11fd61da958f6287a39ff3a3f2c6095888caa3f433R …

fix: add harmony system detection support

---

packages/arcodesign/components/search-bar/README.en-US.md
packages/arcodesign/components/search-bar/README.md
packages/arcodesign/components/search-bar/__ast__/index.ast.json
packages/arcodesign/components/search-bar/__test__/index.spec.js
packages/arcodesign/components/search-bar/association.tsx
packages/arcodesign/components/search-bar/type.ts
scripts/sites/plugins/DemoGeneratePlugin/generate-demo.js

This pull request introduces changes to the `SearchBar` component and associated files to enhance functionality by adding an `event` parameter to the `onAssociationItemClick` callback. Additionally, it includes a minor improvement to demo generation by ensuring valid CSS class names. Below is a breakdown of the most important changes:
* Updated the `onAssociationItemClick` callback across multiple files to include an additional `event` parameter, enabling access to the `MouseEvent` object when a search result item is clicked. This change was applied to:
- Documentation files: `README.en-US.md` and `README.md` [[1]](diffhunk://#diff-2fe04e0deaa8d97eaf2dab825ab5f95a8659c6c3a1683cd409e2cae18cce9216L26-R26) [[2]](diffhunk://#diff-44bdd5a5b7699446e08e805d3c084930c503ae08b73a0fb22c7728e3bc7deb9f …

fix: `SearchBar` add mouse event param to "onAssociationItemClick"

---

packages/arcodesign/components/tabs/README.en-US.md
packages/arcodesign/components/tabs/README.md
packages/arcodesign/components/tabs/__ast__/index.ast.json
packages/arcodesign/components/tabs/index.tsx
packages/arcodesign/components/tabs/type.ts

This pull request updates the `resetUnderlineStyle` method across multiple files in the `tabs` component to clarify its behavior and ensure consistency. The method now explicitly states that it only recalculates the position of the underline style and advises calling `updateLayout` if the tab cell DOM is manually changed. Additionally, the implementation of `updateLayout` has been updated to call `updateLayout` on `cellRef` instead of `resetUnderlineStyle`.
* Updated the description of `resetUnderlineStyle` in `README.en-US.md` and `README.md` to clarify its behavior and include instructions for manual DOM changes. [[1]](diffhunk://#diff-d6199cd697edbca89ba7d47fd111eb68f62261ee6e20ad526d77ca6903b8c378L176-R176) [[2]](diffhunk://#diff-4ca80e81f9f987a7bf72fae0d8be57a56170148701db93eea6875027 …

fix: `Tabs` optimize updateLayout

---

README.md
README.zh-CN.md

This pull request adds a new badge to the `README.md` and `README.zh-CN.md` files, linking to DeepWiki for additional project information.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R22): Added a "Ask DeepWiki" badge linking to the project's page on DeepWiki.
* [`README.zh-CN.md`](diffhunk://#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987R23): Added the same "Ask DeepWiki" badge to the Chinese version of the README.

chore: add DeepWiki badge to README

---

packages/arcodesign/components/popover/hooks/usePosition.ts

This pull request refactors the `usePosition` hook in `usePosition.ts` to improve readability and maintainability by introducing helper functions for setting vertical positioning and adding logic to handle cases where there is insufficient space to display a popover.
* Introduced `setToBottom` and `setToTop` helper functions to encapsulate logic for adjusting the popover's position vertically, reducing code duplication.
* Added a new condition to handle cases where there is insufficient space both above and below the target element to display the popover. The logic now calculates available space above and below and adjusts the position accordingly.

fix: `Popover` adjust edge when popover is too tall

---

packages/arcodesign/components/carousel/index.tsx

This pull request refactors the event handling logic in the `Carousel` component to improve code organization and behavior consistency. The changes primarily involve repositioning the handling of the `bouncingRef` state.
**Refactoring of event handling logic:**
* Moved the logic for handling `bouncingRef` from the `onTouchStart` event to the `onTouchEnd` event, ensuring that bouncing behavior is addressed at the appropriate stage of the touch interaction. (`packages/arcodesign/components/carousel/index.tsx`, [[1]](diffhunk://#diff-97117a9403be52511be91dea02493cea5d06ccb38d5e3d5c905b64583a368465L1037-L1041) [[2]](diffhunk://#diff-97117a9403be52511be91dea02493cea5d06ccb38d5e3d5c905b64583a368465R1046-R1050)

fix: `Carousel` swipping problem after setting "bounceWhenNoLoop"

---

.github/workflows/pr-preview.yml

This pull request updates the GitHub Actions workflow for PR previews to improve permissions handling and simplify the process of creating or updating comments with preview links. The main changes include adding explicit permissions and replacing the `peter-evans` actions with a custom script using `actions/github-script` for better flexibility and maintainability.
* Added explicit `contents: read` and `pull-requests: write` permissions to the workflow, ensuring the necessary access for commenting on pull requests. (`.github/workflows/pr-preview.yml`, [.github/workflows/pr-preview.ymlR6-R9](diffhunk://#diff-737d2247cd4b3b6578d2c5413b555a5ca90f6aaa32613770ffdc146900d0469bR6-R9))
* Replaced the `peter-evans/find-comment` and `peter-evans/create-or-update-comment` actions with a custom …

chore: fix pr preview actions

---

packages/arcodesign/components/tag/__test__/index.spec.js

This pull request enhances the test coverage for the `Tag` and `Tag.List` components in `packages/arcodesign/components/tag/__test__/index.spec.js`. It introduces new test cases to verify component behavior under various scenarios, including mounting/unmounting, event handling, style rendering, and edge cases. Additionally, it improves the organization and clarity of the test descriptions by adding comments in both English and Chinese.
* Replaced individual mount tests with a consolidated test to verify mounting and unmounting behavior across different props.
* Added tests for click event handling, including tag click and close button click, with mock functions to validate callbacks.
* Expanded style rendering tests to include various combinations of props like `type`, `size`, `filleted`, …

test: refactor tests for `Tag` component

---

packages/common-widgets/utils/locale/zh-HK.ts
packages/common-widgets/utils/locale/zh-TW.ts
packages/common-widgets/utils/locale/zh-YUE.ts
sites/pc/static/md/i18n.en-US.md
sites/pc/static/md/i18n.md

ref #345 
This pull request adds support for additional Chinese language variants and updates documentation to reflect these changes. Specifically, it introduces new locale configuration files for Traditional Chinese (zh-TW), Hong Kong Traditional Chinese (zh-HK), and Cantonese (zh-YUE), each providing localized strings for UI components and validation messages. The documentation is also updated to list all supported languages in both English and Chinese guides.
**Locale support enhancements:**
* Added `zh-TW` (Traditional Chinese) locale configuration with component and validation messages in `packages/common-widgets/utils/locale/zh-TW.ts`.
* Added `zh-HK` (Hong Kong Traditional Chinese) locale configuration with region-specific translations in …

feat: add new locales "zh-TW", "zh-HK" and "zh-YUE"

---

packages/common-widgets/utils/locale/it.ts
sites/pc/static/md/i18n.en-US.md
sites/pc/static/md/i18n.md

This pull request adds support for the Italian (`it`) locale to the common widgets package and updates the documentation to reflect this new language option. The main change is the introduction of a comprehensive Italian translation file for UI components and validation messages.
**Italian locale support:**
* Added a new file `packages/common-widgets/utils/locale/it.ts` containing Italian translations for all UI components and form validation messages.
**Documentation updates:**
* Updated the English documentation (`sites/pc/static/md/i18n.en-US.md`) to include Italian (`it`) in the list of supported languages.
* Updated the Chinese documentation (`sites/pc/static/md/i18n.md`) to include Italian (`it`) in the list of supported languages.

fix: add new locale "it"
